const {Router} = require("express")
const userRoutes = require("./userRoutes")
const clientRoutes = require("./clientRoutes")
const testRoutes = require("./testRoutes")
// const { isAuthenticated } = require("../helpers/jwt")
const {validateApiKey} = require("../helpers/apiKey")
const servicesRoutes = require("./servicesRoutes")
const fileRoutes = require("./fileRoutes")
const companyRoutes = require("./companyRoutes")
const indexRoutes = Router()

indexRoutes.use("/user", userRoutes)
indexRoutes.use("/test", testRoutes)
indexRoutes.use("/client", clientRoutes)
indexRoutes.use("/file", fileRoutes)
indexRoutes.use("/company", companyRoutes)
indexRoutes.use("/services",validateApiKey ,servicesRoutes)
// indexRoutes.use("/client",isAuthenticated, clientRoutes)

module.exports = indexRoutes